[package]
name = "fun_motifs_plugin"
version = "0.1.0"
authors = [
  "Daniel Rivas <danielrivasmd@gmail.com>",
]
edition = "2021"

[dependencies]
anyhow = "1.0.31"
clap = "3.1.0"
colored = "2.0.0"
derive-new = "0.5.9"
thiserror = "1.0.37"
